[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:spring-boot]
command=java %(ENV_JAVA_OPTS)s -jar /app/app.jar
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DB_HOST="%(ENV_DB_HOST)s",DB_PORT="%(ENV_DB_PORT)s",DB_NAME="%(ENV_DB_NAME)s",DB_USERNAME="%(ENV_DB_USERNAME)s",DB_PASSWORD="%(ENV_DB_PASSWORD)s",JWT_SECRET="%(ENV_JWT_SECRET)s",APP_USERNAME="%(ENV_APP_USERNAME)s",APP_PASSWORD="%(ENV_APP_PASSWORD)s",TZ="Asia/Shanghai"
priority=20
startsecs=15
startretries=3
